mp:
  jwt:
    verify:
      publickey:
        location: https://dev-00000.okta.com/oauth2/default/v1/keys
      issuer: https://dev-000000.okta.com/oauth2/default

okta:
  client:
    id: ""
    secret: ""
  scopes: openid%20profile%20email

quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      max-size: 64
      url: jdbc:postgresql://localhost:5432/mati
  flyway:
    migrate-at-start: true
