mp:
  jwt:
    verify:
      publickey:
        location: https://dev-00000.okta.com/oauth2/default/v1/keys
      issuer: https://dev-000000.okta.com/oauth2/default

okta:
  url: https://dev-0000000.okta.com
  client:
    id: ""
    secret: ""
  scopes: admin

quarkus:
  http:
    cors:
      origins: "*"
      methods: "*"
      access-control-max-age: -1
      headers: "*"
  datasource:
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mati
    username: postgres
    password: postgres
  flyway:
    migrate-at-start: true
  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
    database:
      generation: none
  swagger-ui:
    always-include: true

"%dev":
  quarkus:
    flyway:
      clean-at-start: true
      log:
        sql: true
      statistics: true

"%prod":
  quarkus.flyway.clean-at-start: false

"%test":
  quarkus.datasource.jdbc:
      driver: org.testcontainers.jdbc.ContainerDatabaseDriver
      url: jdbc:tc:postgresql:13:///mati
